name: SwiftTalk
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  android_intent_plus: ^5.3.0
  google_sign_in: ^6.3.0
  permission_handler: ^11.4.0
  http: ^1.2.0
  flutter_webrtc: ^0.13.0
  uuid: ^4.3.3
  file_picker: ^9.2.1
  flutter_advanced_drawer: ^1.3.5
  firebase_messaging: ^15.2.4
  vibration: ^3.1.3
  aws_storage_service: ^1.1.1
  google_generative_ai: ^0.4.6
  provider: ^6.1.4
  flutter_local_notifications: ^19.0.0
  path_provider: ^2.1.5
  device_info_plus: ^11.3.0
  open_file: ^3.5.10
  googleapis_auth: ^2.0.0
  markdown_widget: ^2.3.2+6
  background_fetch: ^1.3.8
  path: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/logo.png