name: SwiftTalk
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  android_intent_plus: ^5.3.0
  faker: ^2.1.0
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  permission_handler: ^11.2.0
  http: ^1.2.0
  flutter_webrtc: ^0.13.0
  uuid: ^4.3.3
  firebase_storage: ^12.4.4
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  file_picker: ^9.2.1
  chewie: ^1.7.4
  photo_view: ^0.15.0
  flutter_advanced_drawer: ^1.3.5
  flutter_native_splash: ^2.3.10
  qr_code_scanner: ^1.0.1
  intl: any
  firebase_messaging: ^15.2.4
  vibration: ^3.1.3
  speech_to_text: ^7.0.0
  syncfusion_flutter_pdfviewer:
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_datepicker: ^29.1.33
  syncfusion_flutter_core: any
  wakelock_plus: ^1.2.10
  background_fetch: ^1.3.8
  aws_storage_service: ^1.1.1
  path: ^1.9.0
  flutter_animate: ^4.5.2
  markdown_widget: ^2.3.2+6
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
